### ISSUE TITLE
Update dictionary from Wikipedia Indonesia's common spelling mistakes list

### ISSUE THREAD

**Issue by laymonage** [turfaa/IndonesianKataBakuChecker#2]
I think this would be a good additional source for the dictionary:
https://id.wikipedia.org/wiki/Wikipedia:Daftar_kosakata_bahasa_Indonesia_yang_sering_salah_dieja.

You can try parsing the tables with the help of tools such as http://wikitables.geeksta.net and update the dictionary using the data. I made a PR containing some updates from the tables here: https://github.com/turfaa/IndonesianKataBakuChecker/pull/1 :)

**Comment by turfaa** [comment]
@laymonage done! thank you for your suggestion :D
