### ISSUE TITLE
No License found

### ISSUE THREAD

**Issue by yogo-chen** [turfaa/IndonesianKataBakuChecker#3]
Hi @turfaa 

I don't see any license for this repository. 
May I suggest you **GNU General Public License v3.0**?

A short explanation from [Choose an open source license - Choose a License](http://choosealicense.com/)
```
I care about sharing improvements.

The GNU GPLv3 is a copyleft license that requires anyone who distributes your code or a derivative work to make the source available under the same terms, and also provides an express grant of patent rights from contributors to users.
```

**Comment by turfaa** [comment]
@yogo-chen thank you for your recommendation, but I prefer the WTFPL2 license.
I've added it myself.
