### ISSUE TITLE
Incorrect kata baku in dictionary

### ISSUE THREAD

**Issue by adhikasp** [turfaa/IndonesianKataBakuChecker#6]
https://github.com/turfaa/IndonesianKataBakuChecker/blob/master/dict.txt#L392

"salah" is a correct and formal word. It's also an antonym of "benar".

![image](https://cloud.githubusercontent.com/assets/6151302/20032046/76aeca2a-a3b4-11e6-8c70-d1abfa5949d6.png)

It's pretty funny though

**Comment by turfaa** [comment]
@adhikasp thanks! It's beacause I manually parse the dictionary :D

**Comment by turfaa** [comment]
@adhikasp thanks! It's because I manually parse the dictionary :D

**Comment by turfaa** [comment]
@adhikasp thanks! It's because I manually parse the dictionary :D
